import type { Metadata } from "next";
import "./globals.css";
import RootLayoutClient from "@/components/root-layout-client";

export const metadata: Metadata = {
  title: "Metadrinks",
  //description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <RootLayoutClient>{children}</RootLayoutClient>
      </body>
    </html>
  );
}
