import type { Metadata } from "next";
import "./globals.css";
import RootLayoutClient from "@/components/root-layout-client";
import { PublicEnvScript } from "next-runtime-env";

export const metadata: Metadata = {
  title: "Metadrinks",
  //description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <meta name="apple-mobile-web-app-capable" content="yes" />
        <meta name="apple-mobile-web-app-status-bar-style" content="default" />
        <meta name="theme-color" content="#ffffff" />
        <PublicEnvScript />
      </head>
      <body>
        <RootLayoutClient>{children}</RootLayoutClient>
      </body>
    </html>
  );
}
